### ISSUE TITLE
Populate music library with real metadata

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/hyperamp#11]
I've fooled around with [musicmedata](https://www.npmjs.com/package/musicmetadata) and [fs-walk](https://www.npmjs.com/package/fs-walk) a bit but don't have anything concrete yet. @bcomnes let me know if you want to take a crack at this.

**Comment by bcomnes** [comment]
I wanted to try to use https://www.npmjs.com/package/folder-walker, but yeah, give it a shot if you want to. https://www.npmjs.com/package/musicmetadata looks good to me.

**Comment by ungoldman** [comment]
@bcomnes I might switch gears but I'll claim the task here if I get on a roll. If you get some free time and want to take it just claim it before I do 😉

**Comment by bcomnes** [comment]
ok sounds good

**Comment by ungoldman** [comment]
Working on this now
