### ISSUE TITLE
Fix artwork loading on app initialization 

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#120]
Right now artwork only shows on queue.  We should trigger this when the app initializes too.

**Comment by ungoldman** [comment]
hey @bcomnes what's the status on this issue? would love to see that album art on reload.

**Comment by bcomnes** [comment]
Closing in favor of https://github.com/hypermodules/hyperamp/issues/119 since that work needs to get done in order to solve this, and it can just be incorporated.
