### ISSUE TITLE
Choo 5

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#124]
https://medium.com/@yoshuawuyts/choo-v5-bc775b007b5e#.te9h0j6w5
https://github.com/yoshuawuyts/choo/pull/425/files

The api changes a bunch, but the good news is that it will make our lives a lot easier.  

It has built in components, makes state mutable so we aren't generating garbage piles of song lists every time you change the volume, and uses event emitters directly which more closely mirrors how the main thread is working right now.

**Comment by zeke** [comment]
🚂

**Comment by bcomnes** [comment]
Closed by https://github.com/hypermodules/hyperamp/pull/127
