### ISSUE TITLE
Sticky table headers

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#17]
We need to do sticky table headers, so you can adjust the sort column and direction when you are at any scroll position.

Ideally, we could just use something like [Sticky Positioning](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning), but it doesn't work on `thead` elements, and it doesn't work in chrome webkit! 😭

There are a bunch of [hacks](http://stackoverflow.com/questions/1030043/html-table-headers-always-visible-at-top-of-window-when-viewing-a-large-table) that you can do to get it to sort of work with the table elements, but they are all pretty gross and don't perform great.  

The third options I was thinking of is dropping the `table` component all together and using flex'd div's with `overflow: auto` set on the table row container.  We are going to have to port over/redo table styles, but will ultimately set us to up to do fun/complicated table rows without having to fight the limitations of the archaic table element.  e.g.

<img width="1139" alt="screenshot 2016-08-14 21 48 23" src="https://cloud.githubusercontent.com/assets/166301/17655925/dc835b64-6268-11e6-840c-4c9e8a25edd5.png">

**Comment by ungoldman** [comment]
I'm okay with using flex -- was thinking this might be the road to go down eventually anyway if we want to have alternate display styles (album art, etc). The only part that might be a little complicated is getting header columns to line up with body content, but I think flex should make that fairly easy. I went through http://flexboxfroggy.com a while back, was a great crash course in flexology.

**Comment by bcomnes** [comment]
There is also the `<position: relative><position:absolute /></>` route, but overflow seems a little bit more direct of an approach.  

Yeah, I too am also worried that keeping column with in sync with a shared width variable across a bunch of elements might bring some weirdness into the mix, but I don't see a better alternative so far.

**Comment by ungoldman** [comment]
@bcomnes I think [justifying content](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content) and using even percentage widths as a starting point should do it. One tricky part might be allowing for a slider control to expand/contract column widths, but keeping column heasers in sync with a shared array of width values should be fairly easy.
