### ISSUE TITLE
move audio logic to hidden worker instance

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/hyperamp#18]
I think we should work on moving the audio component to a worker process like we discussed a while back. [Webtorrent Desktop](https://github.com/feross/webtorrent-desktop/tree/master/src/renderer) did this fairly well (even had a keyboard shortcut for exposing the hidden renderer process for debugging I think).

The implementation has grown a somewhat unnecessarily complex (see [main/windows/webtorrent.js](https://github.com/feross/webtorrent-desktop/blob/master/src/main/windows/webtorrent.js) and [renderer/webtorrent.js](https://github.com/feross/webtorrent-desktop/tree/master/src/renderer/webtorrent.js)) and they decided to port the entire project to React for some reason (😢) but I think we can draw a lot from the basic parts of the method used there.

**Comment by ungoldman** [comment]
This would allow us to more easily open/close the library window while the player is still going and also include a menubar process. The three could communicate and stay in sync with IPC messages. Only caveat is I think we'd need to manage communication between renderer processes on the main thread using [ipcMain](https://github.com/electron/electron/blob/master/docs/api/ipc-main.md) since I think [ipcRenderer](https://github.com/electron/electron/blob/master/docs/api/ipc-renderer.md) can only communicate with the main thread and not renderer siblings. That should work out well though since we probably want the main thread to act as the canonical store for audio state.

**Comment by bcomnes** [comment]
This sounds like a good next step, although I am curious to see if there are any advantages to using any of the [c++ libs](https://github.com/hypermodules/hyperamp/wiki/Audio-Decoding-Libs) or http://audiocogs.org library outside of a window process.

**Comment by ungoldman** [comment]
Might be worth investigating but be warned packaging an electron app for distrubition and including compiled/native code from a third party is not an obvious problem to solve (at least for me in the past).

**Comment by bcomnes** [comment]
I think it depends on the native module packaging.  Some require unbundled external shared libraries (like imagemagic right?) and others bundle the dependency into the native module (like https://github.com/paixaop/node-sodium) that can be fully installed with npm when the build environment has the gyp requirements (e.g. c++ compiler, python etc.)  

I've never done packaging for something like that before, so there are sure to be sharp edges, but I *think* its possible. Learning more about how to bind to C/C++ libraries is also something I've been interested in learning how to do for a while.
