### ISSUE TITLE
More compact table view

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#186]
I like the mobile app-like sidebar, I don't want to see that go away, but I want to get back a more compact table view, since horizontal space become valuable in table views when you are working with smaller window sizes.  

I was thinking about going back to something like this:

![img_1418](https://user-images.githubusercontent.com/166301/27256070-3caee556-5360-11e7-8a39-6bdeb56c3f0a.JPG)

(yes my handwriting is about as good as 3rd graders)

**Comment by bcomnes** [comment]
We could then have a compact mode that does something similar to what we have now:

![screen shot 2017-06-17 at 1 25 30 pm](https://user-images.githubusercontent.com/166301/27256085-91133764-5360-11e7-9ddd-19050490b5f7.png)

![screen shot 2017-06-17 at 1 25 37 pm](https://user-images.githubusercontent.com/166301/27256086-98b0130c-5360-11e7-8f50-3ce48fa9760b.png)

![screen shot 2017-06-17 at 1 25 49 pm](https://user-images.githubusercontent.com/166301/27256087-9b47bfb6-5360-11e7-8594-e89a0ea2cbce.png)

I also want to make the album art click-able opening a default image viewer of the cached copy.

**Comment by bcomnes** [comment]
This kind of iconography is decent:

![screen shot 2017-06-17 at 1 34 06 pm](https://user-images.githubusercontent.com/166301/27256131-b87a2b40-5361-11e7-9203-c775f108f02d.png)

![screen shot 2017-06-17 at 1 34 06 pm](https://user-images.githubusercontent.com/166301/27256132-ba932bb6-5361-11e7-92f4-19401a66ab9f.png)

Maybe we can toggle between the two/three views.

**Comment by bcomnes** [comment]
Capturing design screenshots from @ungoldman 

![screen shot 2017-09-21 at 5 04 28 pm](https://user-images.githubusercontent.com/166301/31869380-5ce9e6a8-b75c-11e7-9402-838843d0cb92.png)

![screen shot 2017-09-21 at 5 06 52 pm](https://user-images.githubusercontent.com/166301/31869381-5ede886a-b75c-11e7-97e1-1fd927ff317d.png)

![screen shot 2017-09-21 at 7 35 12 pm](https://user-images.githubusercontent.com/166301/31869385-6152fbbc-b75c-11e7-9a7e-06ab86732e16.png)

<img width="392" alt="screen shot 2017-09-27 at 3 02 08 pm" src="https://user-images.githubusercontent.com/166301/31869387-6401389c-b75c-11e7-8584-9a7ebc6fa95b.png">

![screen shot 2017-09-27 at 1 14 41 pm](https://user-images.githubusercontent.com/166301/31869394-6b09d50e-b75c-11e7-8cf1-0826bb833434.png)

**Comment by ungoldman** [comment]
Another quick concept sketch based on combining a couple of ideas from above.

![screen shot 2017-11-30 at 4 10 52 pm](https://user-images.githubusercontent.com/427322/33461881-45e69004-d5e9-11e7-93ff-61609287cd13.png)

**Comment by bcomnes** [comment]
I like it
