### ISSUE TITLE
Can't play songs with a # in the filename

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#200]
Songs that have  `#` in the filename won't play.  Probably because the audio tag thinks its a URL hash.  We need to escape that or something.

**Comment by ungoldman** [comment]
I think the [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) method should do the trick

**Comment by bcomnes** [comment]
Turns out we already solved this for the artwork cache using [file-url](http://ghub.io/file-url).  And yeah it is a matter of URL encoding the file path segments, which is slightly more involved than a straight encodeIURIComponent.
