### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#203]
When songs change, we should show a notification, preferably with the artwork or the app icon if its available.

**Comment by ungoldman** [comment]
should be pretty easy, i've tooled around with the osx notifications api via electron before

**Comment by bcomnes** [comment]
Maybe only when the window is closed.

**Comment by ungoldman** [comment]
yeah would be nice to be able to toggle it too, getting song notifications when you're using another fullscreen app can be pretty annoying

**Comment by ungoldman** [comment]
Some more things to think about for notification behavior https://electron.atom.io/docs/tutorial/notifications/#macos

**Comment by ungoldman** [comment]
done:
- [x] notifications

todo:
- [ ] add pref to disable notifications
- [ ] add album art to notification

**Comment by bcomnes** [comment]
Updating the issue on this.  I removed it from the a renderer with plans to move it to the main thread https://github.com/mikaelbr/node-notifier because the window process notifications didn't stack and were quite spammy in practice.
