### ISSUE TITLE
album art view design ideas

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/hyperamp#206]
Working on #205 got me thinking about a reworked album art view. Here are some hastily scribbled notes.

![fullsizerender](https://user-images.githubusercontent.com/427322/27759877-97e71472-5def-11e7-8ca2-fed2fb41c4cd.jpg)

Basically I really like the simple square view and would like the controls to be usable in that state, and I think a stripped-down adaption of a video player interface would do the trick.

![screen shot 2017-06-30 at 11 56 02 pm](https://user-images.githubusercontent.com/427322/27759883-b12d1cba-5def-11e7-960b-6ab931a997db.png)

Definitely borrowing some ideas from the webtorrent player:

![](https://webtorrent.io/img/screenshot-player2.png)

**Comment by bcomnes** [comment]
That would look really cool. 💯

**Comment by bcomnes** [comment]
What do you think abut a stacked table view e.g. https://github.com/hypermodules/hyperamp/issues/186?

**Comment by bcomnes** [comment]
I did this a while back with canvas: 
![screen shot 2017-07-01 at 9 32 21 am](https://user-images.githubusercontent.com/166301/27763840-4d632156-5e40-11e7-9014-f42adb7aba7e.png)

Would be cool to do time stamps and spectral with the 1px needles, then you just click and drag around.  Also make it less ugly.

**Comment by bcomnes** [comment]
Experimented with in-line artwork.
