### ISSUE TITLE
feature: skip to next/previous song

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/hyperamp#22]
The user should be able to skip to both the next and previous song in the current list (or search context).

**Comment by ungoldman** [comment]
Should be able to hook into [media events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events) to allow automatically playing the next song, e.g.

```js
audio.addEventListener('ended', next)
```

where `next` is a function that loads the next track based on a cached playlist.

**Comment by bcomnes** [comment]
Closed by https://github.com/hypermodules/hyperamp/pull/96
