### ISSUE TITLE
Register LLC

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#221]
http://sos.oregon.gov/business/Pages/register.aspx

**Comment by zeke** [comment]
why?

**Comment by ungoldman** [comment]
@zeke for shared access to distribution certificates, methinks: https://github.com/hypermodules/hyperamp/issues/92

**Comment by bcomnes** [comment]
Yeah, so we can sign with hypermodules llc instead Bret McDuck Inc ;P

**Comment by bcomnes** [comment]
The motivation to start signing is that I'm starting to use HA on a regular enough basis that I want to set up autoupdates and real builds.

**Comment by ungoldman** [comment]
👍 me too! would be great to have auto-updating nightly builds or something with a dependable enough CI that we're not pushing showstopping bugaroos

**Comment by bcomnes** [comment]
This is done! http://egov.sos.state.or.us/br/pkg_web_name_srch_inq.show_detl?p_be_rsn=1933842&p_srce=BR_INQ&p_print=FALSE
