### ISSUE TITLE
add chromecast support

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/hyperamp#222]
would be nice to cast music to various media devices. I think [chromecasts](https://github.com/mafintosh/chromecasts) would do the trick (used by [playback](https://github.com/mafintosh/playback))

**Comment by bcomnes** [comment]
I use bluetooth at home, but yeah I agree that would be cool.

**Comment by zeke** [comment]
what do you mean when you say you use bluetooth at home?

**Comment by bcomnes** [comment]
I just use bluetooth speakers from my laptop, vs chromecast over wifi.

**Comment by zeke** [comment]
oh duh right I saw the word chromecast and lapsed into thinking hyperamp is also a video player. 🙈

**Comment by bcomnes** [comment]
One day...  one day
