### ISSUE TITLE
Now playing UI element

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#23]
We need to implement a now playing info panel that shows the currently playing song, scrubber and time etc.

**Comment by bcomnes** [comment]
<img width="538" alt="screenshot 2016-08-26 09 16 05" src="https://cloud.githubusercontent.com/assets/166301/18012305/d790338a-6b6d-11e6-9682-1ee0ff6de684.png">

**Comment by bcomnes** [comment]
<img width="1133" alt="screenshot 2016-08-26 09 17 49" src="https://cloud.githubusercontent.com/assets/166301/18012376/fc11fe1e-6b6d-11e6-8318-2eabe5302a5f.png">

**Comment by ungoldman** [comment]
Yep, agreed! This ties in with #21 too.

**Comment by ungoldman** [comment]
bump

**Comment by ungoldman** [comment]
working on this now
