### ISSUE TITLE
bug: major slowdown since audio library udpate

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/hyperamp#237]
Experiencing major slowdown in responsiveness of renderer after loading a large library (~50gb)

<img width="1392" alt="screen shot 2017-10-08 at 4 41 47 pm" src="https://user-images.githubusercontent.com/427322/31322181-ab323966-ac47-11e7-9e42-7b7f3e6262a6.png">

**Comment by ungoldman** [comment]
Seems like it's actually the logger (choo-log) that's crapping out... Calling an unoptimized `_clone` function a million times on every event.

**Comment by ungoldman** [comment]
ok actually it's choo-devtools. https://github.com/choojs/choo-devtools/blob/master/lib/log.js#L41

**Comment by ungoldman** [comment]
cloning the entire state object, including an array of ~9000 track objects, every single time there's an event (`emitter.on('*'`)

**Comment by ungoldman** [comment]
maybe we should trick the track dict as a db and offload it to main, then render slices provided by main? rather than moving around a giant track dict between various threads / windows

**Comment by bcomnes** [comment]
Adds a large amount of latency during scrolling. I tried that using require remote awhile ago. You are better of moving the objects out of choo state and using a shared module object for lookups when needed

**Comment by ungoldman** [comment]
it works fine when `choo-devtools` is not used, so maybe that's the right thing to do short-term

**Comment by ungoldman** [comment]
Fixed in https://github.com/choojs/choo-devtools/pull/11 & 951278a994b3b6fa47e8e5bd8487a2fceb1496a7.
