### ISSUE TITLE
feature: keyboard shortcuts

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/hyperamp#24]
The user should be able to control playback via keyboard shortcuts.

Basic defaults:
- <kbd> space </kbd>: play/pause
- <kbd> → </kbd> / <kbd> ← </kbd>: skip to next or last
- <kbd> ↑ </kbd> / <kbd> ↓ </kbd>: move highlighted selection in media list

These can be attached to menu items so that we can use the menu/keyboard shortcut mapping methods provided by electron.

**Comment by bcomnes** [comment]
We should also write a provider for http://beardedspice.github.io

**Comment by ungoldman** [comment]
@obensource mentioned being interested in helping out with our little project -- I think this issue would be a fairly approachable starting point. (don't worry about the `beardedspice` thing).

**Comment by bcomnes** [comment]
I would love to see PRs by @obensource 👍 That would be awesome.  Yeah ignore the bearded spice thing, that can be done later.

**Comment by bcomnes** [comment]
I added some media playback button registration but it can be taken away by other apps.  We need to trigger registration on window activation, and also add the ones listed in the OP.

https://github.com/hypermodules/hyperamp/blob/master/main/index.js#L193-L195

**Comment by bcomnes** [comment]
This is toats done.
