### ISSUE TITLE
Sorting out sort

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#275]
Our sort doesn't group albums together correctly.  A lowercased filepath sort might work better than what we are doing now, assuming people organize their music the way iTunes would.  

https://github.com/hypermodules/hyperamp/blob/master/main/lib/audio-library/sort.js

**Comment by ungoldman** [comment]
@bcomnes We've talked about this before and I still disagree. We can't rely on file paths to drive sorting. If there's an issue with the sorting algorithm we should just fix that. Also makes no sense to me to give up on a proper album sort while also trying to do column sorts (#276).
