### ISSUE TITLE
Column sorts

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#276]
It was requested by dog_awoo that the columns sort the music.  I think a good `Artist -> Album Year -> Album` sort is all anyone would ever need, but column sorting is such a familiar pattern and fairly easy to implement at some level that we should probably just add it.

**Comment by autonome** [comment]
When listening to an album, I want to sort by track number in order to experience the music in the way the artist designed so it can speak more clearly to my soul and transcend the physical boundaries we chafe against.

**Comment by bcomnes** [comment]
Agree, lol. 

It should sort by track number by default.  Never got around to this.
