### ISSUE TITLE
Dynamic color

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#281]
Use album artwork to come up with a dynamic color scheme like iTunes does.

https://github.com/FormidableLabs/react-image-palette/blob/master/src/get-image-palette.js

Would be great to extract that out into its own module, and then consume it here.

![qodsu](https://user-images.githubusercontent.com/166301/32793805-d4c1f7f8-c91b-11e7-956d-50cf32f351f7.png)

**Comment by kareniel** [comment]
Theres `color-thief` on npm:

```js
var ColorThief = require('color-thief')
var colorThief = new ColorThief()
var color = colorThief.getColor(image)
```

**Comment by kareniel** [comment]
There's `color-thief`on NPM that could come in handy (it's not framework specific like `react-image-palette`):

```js
var ColorThief = require('color-thief')
var colorThief = new ColorThief()
colorThief.getColor(image)
```

You can also get multiple colors if needed (could be useful for finding complementary colors that are found in the album art) with `colorThief.getPalette(image, numberOfColors)`

**Comment by bcomnes** [comment]
Nice find!
