### ISSUE TITLE
Our sick   artwork placeholder has gone missing

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#286]
![screen shot 2017-12-03 at 4 28 14 pm](https://user-images.githubusercontent.com/166301/33531792-0a8df0e6-d847-11e7-97f6-47e95d048c47.png)

**Comment by ungoldman** [comment]
My bad, I moved the splash image to `static` folder, forgot it was used somewhere besides the readme.

**Comment by ungoldman** [comment]
Turns out the path was fine, just that `buildResources` gets ignored by `electron-builder`.

Working on a PR that reworks directories again, which should fix this issue as well.
