### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/hyperamp#298]
We need to write down the release process in the "Developing" section of [CONTRIBUTING.md](https://github.com/hypermodules/hyperamp/blob/master/CONTRIBUTING.md#developing).

**Comment by ungoldman** [comment]
👉 @bcomnes when you have time, would be good to get release process info written down so I can create releases too. If it's just a matter of following a process established by `electron-builder`, a link to that would be good enough for now.

**Comment by ungoldman** [comment]
Is this it? https://github.com/electron-userland/electron-builder/blob/2eb9b1f096cc7587c70b531bde5b28e69e7b3086/docs/configuration/publish.md#recommended-github-releases-workflow

**Comment by bcomnes** [comment]
Essentially.  

If I can remember from memory:

- Bump the version in package.json
- Create a draft 
- All commits/merges to master will start uploading builds
- When you are happy, do an empty -m 'X.X.X' commit on master and let it finish and make sure it uploaded to the draft.
- Publish the draft with a `vX.X.X` format (auto-update is picky about URL names.)
- Clients will get that next time the start.
