### ISSUE TITLE
Try out standard-version?

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/hyperamp#299]
Managing releases is a bit laborious -- one thing we could automate is change logs and version numbers.

I've tried out a couple different solutions and have found [standard-version](https://github.com/conventional-changelog/standard-version) to be the best so far.

One caveat is that it requires writing commits in a very specific way ("conventional commits"). See https://conventionalcommits.org/ for more info on that.

The advantage is if you write your commits in this format, a readable, well-formatted change log can be automatically generated, and appropriate version bumping with semver can be be inferred from the commits themselves (fixes, features, breaking changes).

Let me know if you're willing to try it out @bcomnes.

**Comment by zeke** [comment]
`npm i -g semantic-release && cd cool-project && semantic-release-cli setup` is working wonders for me.

If you forget to write conventional commit messages, you can rewrite a semantic message with a squash or merge commit message.

**Comment by bcomnes** [comment]
Yeah let’s try it

**Comment by ungoldman** [comment]
@zeke my main gripe with `semantic-release` is that it doesn't update the version in `package.json`. I understand their [reasoning](https://github.com/semantic-release/semantic-release#why-is-the-packagejsons-version-not-updated-in-my-repository), I just disagree with it.

**Comment by bcomnes** [comment]
Just read that. Weird, they don’t really justify why they don’t update it, only about why it happens to work.

**Comment by zeke** [comment]
I think the idea is that as soon as your code changes, the value of `version` in package.json is no longer reflective of reality. I found this a little odd at first too, but just decided to let go and haven't looked back.

If you end up using `standard-version`, please share your thoughts on it!

**Comment by bcomnes** [comment]
Oh I guess that makes sense.

**Comment by bcomnes** [comment]
https://user-images.githubusercontent.com/166301/224850334-85c3558b-98bf-4081-b85d-1000c67149ff.mp4

**Comment by ungoldman** [comment]
RIP 🫡
