### ISSUE TITLE
Searching and sorting by genre

### ISSUE THREAD

**Issue by zeke** [hypermodules/hyperamp#307]
Greetings hyperfolks. 👋 

It looks like "genre" was mentioned in https://github.com/hypermodules/hyperamp/issues/1 but didn't make it into hyperamp's columns, and the search doesn't appear to include genre either. Are there Reasons™ it was omitted? If not, can we make it happen?

**Comment by ungoldman** [comment]
Feature request landed in #309, should be released later this evening.

**Comment by ungoldman** [comment]
Released in [0.5.13](https://github.com/hypermodules/hyperamp/releases/tag/v0.5.13)!

Btw @zeke I added release-notifier to all hypermodules repos when you first published it and have not seen it work yet.

Also of note: sorting by column is still a thing we need to work on. PRs always welcome.

**Comment by ungoldman** [comment]
See also #275 #276

**Comment by zeke** [comment]
>  I added release-notifier to all hypermodules repos when you first published it and have not seen it work yet.

Yeah I know I broke it sorry. I'll fix it soon.
