### ISSUE TITLE
NaN:NaN

### ISSUE THREAD

**Issue by zeke** [hypermodules/hyperamp#310]
![image](https://user-images.githubusercontent.com/2289/37185619-15f62ac6-22f6-11e8-8308-cf09a4ad9f37.png)

**Comment by bcomnes** [comment]
We cant extract time data from some files yet.  I have an idea for a workaround that I haven't had time for yet.

**Comment by ungoldman** [comment]
Might want to also update https://github.com/ungoldman/format-duration to handle invalid arguments more betterfully.
