### ISSUE TITLE
link in repo header no workie

### ISSUE THREAD

**Issue by jgravois** [hypermodules/hyperamp#35]
http://hypermodul.es/hyperamp > http://hypermodul.es?

this is a cool project!!!

**Comment by ungoldman** [comment]
Removed for now since it doesn't exist.

@bcomnes if we want to have a `gh-pages` branch here that lives at http://hypermodul.es/hyperamp, I think we may need to rename the https://github.com/hypermodules/hypermodul.es repo to `hypermodules.github.io`.

**Comment by jgravois** [comment]
you can host from the `master` branch now too!
https://github.com/blog/2228-simpler-github-pages-publishing

**Comment by bcomnes** [comment]
Oh yeah, I'm not sure how the recent changes has affected that.  The URL was a pre-emptive thing.  Lets plan to re-add it back once someone puts something there.

@jgravois thanks!  I've been intending to maintain some roadmap notes nate and I have loosely discussed to keep the project accessible to contributions.
