### ISSUE TITLE
Ponder a divergence from OS X UI style. definitely

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#37]
Quick thought here: no other electron app uses the OS X style, and instead diverges into something kind of endogenous between all the OSs.  

For now, I'm going to try to stick to the photon UI style, but I'm thinking of ways to maybe make things easier in the long run.

As work progresses to re-implement some of the UI elements to meet our needs (e.g.  https://github.com/hypermodules/flex-table) maybe we should start considering something less specific to OS X.  It might make CSS easier, and buy is a look that works on Linux and Windows.

Examples:

![screen shot 2016-09-22 at 9 58 00 am](https://cloud.githubusercontent.com/assets/166301/18758179/d44f9b04-80ab-11e6-9aa4-11558c8b5f72.png)

Tha table implementation is an interesting example in BTSync

![screen shot 2016-09-22 at 10 08 03 am](https://cloud.githubusercontent.com/assets/166301/18758340/7b6df692-80ac-11e6-9d7d-5294e95885db.png)

**Comment by bcomnes** [comment]
Turns out the btsync app lets you inspect the UI on the linux version.  Looks like the trick to get a sticky headers tables using `<table>` and `<colgroup>` is to use two separate tables separated by a an overflow: auto/scroll div wrapping the scroll part. 

I'll prob just switch over to that.  Not much time lost.

**Comment by ungoldman** [comment]
sgtm thumbs up bro

**Comment by ungoldman** [comment]
also totally fine with diverging from os x style. it's kinda boring, and photon is missing a lot of pieces. down with trying to start to try to define our own style component by component

**Comment by ungoldman** [comment]
I saw this style recently and liked its simplicity, may try to do something in a similar vein https://github.com/terkelg/ramme

![](https://github.com/terkelg/ramme/raw/master/media/screenshot-dark.png)

**Comment by bcomnes** [comment]
I like it

**Comment by bcomnes** [comment]
I've been reading through https://www.bignerdranch.com/we-write/cocoa-programming/ and all about the neato stuff the apple has implemented in their table views over the last 20 years and its making me depressed. 

I'm going to instead just do a fairly static `Album by Artist/Year` table + a search filter, (the view that I generally use 99% of the time) to get layout right and that way we can avoid the complexity around table controllers and things like sort  stacks and bindings between the view and the choo model.

That is this sort: 

<img width="1139" alt="screenshot 2016-08-14 21 48 23" src="https://cloud.githubusercontent.com/assets/166301/17655925/dc835b64-6268-11e6-840c-4c9e8a25edd5.png">

**Comment by bcomnes** [comment]
More blue style

![screen shot 2016-12-13 at 10 40 02 am](https://cloud.githubusercontent.com/assets/166301/21153707/85d05b5c-c120-11e6-88ef-af4048549c7d.png)

**Comment by bcomnes** [comment]
![screen shot 2016-12-13 at 10 48 18 am](https://cloud.githubusercontent.com/assets/166301/21154138/1bd9c740-c122-11e6-8f35-ff3c2a6934ec.png)

**Comment by ungoldman** [comment]
Approaching darkness

![screen shot 2016-12-16 at 11 43 21 am](https://cloud.githubusercontent.com/assets/427322/21276121/df89062e-c384-11e6-9689-915d3cfdfffc.png)

**Comment by bcomnes** [comment]
Done by the work this weekend I think.
