### ISSUE TITLE
Use Camel case CSS properties

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#64]
Out with the old, in with the new.  Why use kebab case for css class names just because people in the aughts did it that way.  Lets just use camel case property names to keep selector syntax simple.

**Comment by ungoldman** [comment]
As a curmudgeon, I like kebabs in CSS.

BUT

`styles.camelCase` seems better than `styles['kebab-case']`.

THEREFORE

I endorse this issue.

**Comment by bcomnes** [comment]
Crazy idea:

- kebab-case: global css selectors
- camelCase: csjs selectors

**Comment by bcomnes** [comment]
ok fixed by https://github.com/hypermodules/hyperamp/commit/08dfa82cb636f05cd7e66442720e4d7e328ae89c
