### ISSUE TITLE
Break svg sprite sheet off into its own module

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#66]
Basically, package up http://www.entypo.com as a module with its own prepublish build script.  Some labor involved, but everything is laid out, and the npm name is available.

The module should ship the raw svgs, and a sprite sheet with an `en-` prefix or something.  Model it off https://github.com/Kriesse/dat-icons.  I think I love this pattern.

**Comment by bcomnes** [comment]
Done by https://www.npmjs.com/package/entypo and https://github.com/hypermodules/hyperamp/commit/f2e5da0de7db353006c560f8c7b42e8d5bcfb43b

**Comment by ungoldman** [comment]
cool 👍
