### ISSUE TITLE
Refreshing broken after navigation.

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#68]
![bug](https://cloud.githubusercontent.com/assets/166301/21284534/a62f978c-c3d2-11e6-865a-d530182a715f.gif)

This was another sheet-router bug I was running into.  Basically, refreshing the app should work everywhere, but after you navigate around, you lose the base url so subsequent refreshes fail.  The gif shows 1 working refresh (initial state) and one failed refresh at the end.  I need to open an issue upstream.  Going to  🛏 goodnight 🌖

**Comment by ungoldman** [comment]
Yep, reported here: https://github.com/yoshuawuyts/sheet-router/issues/72

**Comment by bcomnes** [comment]
Possible hints https://gist.github.com/yoshuawuyts/ad04f4057586c28ede7e33d898c1a202

**Comment by bcomnes** [comment]
By pushing back our goals on the project, this issue can be put off for now, as we don't even need a preference pane to do a single playlist interface.

**Comment by bcomnes** [comment]
I switched to using hash based views and this worked again.  Since we are doing file based view loading, using hashes makes more sense anyway.
