### ISSUE TITLE
Handle ∞ long lists

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#80]
Here are some things that might be useful 

- https://github.com/shama/csv-viewer
- https://github.com/shama/view-list
- https://github.com/editdata/data-grid
- https://github.com/yoshuawuyts/base-elements
- https://clusterize.js.org
- datatables.net/extensions/ + https://datatables.net/extensions/scroller/

**Comment by ungoldman** [comment]
https://github.com/editdata/infinite-elements

via @sethvincent 💪😎👍

**Comment by bcomnes** [comment]
https://github.com/tbranyen/hyperlist recomended by @ungoldman looks really nice, probably start there.   I would say this looks like next step for me, superseding the artwork server idea I had.

**Comment by bcomnes** [comment]
![screen shot 2017-05-16 at 6 39 12 pm](https://cloud.githubusercontent.com/assets/166301/26135005/5866b1b4-3a67-11e7-987d-4c14bce79dbf.png)

**Comment by ungoldman** [comment]
@bcomnes perfect! ship it

**Comment by bcomnes** [comment]
https://github.com/timwis/choo-infinite-list

**Comment by bcomnes** [comment]
> ungoldman> ungoldman@gmail.com some more infinite scroll research material
01:19 http://googlechrome.github.io/ui-element-samples/infinite-scroller/
01:19 https://github.com/GoogleChrome/ui-element-samples/tree/gh-pages/infinite-scroller
