### ISSUE TITLE
Do css like ungoldman would

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#84]
@ungoldman if you did css for hyperamp all on your own, how would you do the CSS? We kinda talked about this in person.  Would it be worth while to change how we do things once again, if it represents your ideals?  I'd be open to whatever you want to do here.

**Comment by ungoldman** [comment]
I'd be willing to figure out how it is that I would do the CSS. From what I remember my ideal was using postcss-cssnext with some globally defined defaults and component-specific stylesheets living next to the component in the related directory, then building it all to a single build file.

**Comment by ungoldman** [comment]
Would be nice to have a task to what for changes and rebuild too. Not too hard to do.

**Comment by bcomnes** [comment]
Closing this overly open-ended issue.  @ungoldman feel free to make any changes/open specific issues regarding changes to the css that you feel compelled to make.
