### ISSUE TITLE
Add a couple electron nice-to-haves

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#90]
We do this stuff manually now.  Would be nice to clean it up with:

- [x] https://github.com/carter-thaxton/electron-default-menu
~~- [ ] https://github.com/jprichardson/electron-window~~ nah for now maybe later.

**Comment by ungoldman** [comment]
https://www.npmjs.com/package/electron-window-state

**Comment by ungoldman** [comment]
https://github.com/bengourley/choo-resume

**Comment by bcomnes** [comment]
Breaking off the HMR stuff into its own thread as the PR I just sent in is wired up to close this.
