### ISSUE TITLE
Buy macOS Distribution Certificates

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#92]
Damn, this is going to cost about $200 :(

**Comment by ungoldman** [comment]
wat

for macos?

**Comment by bcomnes** [comment]
100 bucks for macOS and about 100 bucks for windows.

**Comment by ungoldman** [comment]
dang bro

**Comment by bcomnes** [comment]
The other benefit of doing this in an org is that one perk offered to contributors could be access to signing certificates for whatever other electron apps people want to publish.

**Comment by blahah** [comment]
I just recently bought a macOS developer account - happy to share the cert for signing

**Comment by bcomnes** [comment]
Might take you up on that when we are ready to release.

**Comment by ungoldman** [comment]
@blahah: awesome! thanks!

@bcomnes: happy to split costs if I didn't mention it already IRL

**Comment by zeke** [comment]
I want in too! 😛

**Comment by zeke** [comment]
Would be really cool if we could make this work and share the model with the community.

**Comment by bcomnes** [comment]
It's basically the keys to a botnet in duiguise of an auto update system. I would be open to defining an editorialized application process though. I want to get HA signed first though so I understand the process better

**Comment by bcomnes** [comment]
HYPERMODULES LLC

http://egov.sos.state.or.us/br/pkg_web_name_srch_inq.show_detl?p_be_rsn=1933842&p_srce=BR_INQ&p_print=FALSE

Waiting for my DUNS number from apple now.

**Comment by bcomnes** [comment]
Ok this is done.  LMK if you want access to the apple certs.  Making a new issue for windows certs.
