### ISSUE TITLE
app icon

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/hyperamp#97]
Hyperamp needs an app icon!

Here's an example of how to set it up:

- https://github.com/feross/webtorrent-desktop/tree/master/static
- https://github.com/feross/webtorrent-desktop/blob/master/src/config.js#L28
- https://github.com/feross/webtorrent-desktop/blob/master/bin/package.js#L136

**Comment by bcomnes** [comment]
Some ideas:

I like the 45 RPM geometry.  Maybe we can do something like this and use the extra space in the middle for some neat details like the name hyperamp:
![45rpm](https://cloud.githubusercontent.com/assets/166301/25309055/490d72a0-2777-11e7-8b27-ca7d2990841d.jpg)

I really like the old capital record fonts and design:

![476412](https://cloud.githubusercontent.com/assets/166301/25309060/6aed3c34-2777-11e7-9a3e-ed2922b293cf.jpg)

http://www.dafont.com/forum/read/207415/font-capitol-records

<img width="838" alt="screen shot 2017-04-22 at 4 17 24 pm" src="https://cloud.githubusercontent.com/assets/166301/25309063/724f762c-2777-11e7-821b-e56376dfe4a8.png">

<img width="432" alt="screen shot 2017-04-22 at 4 17 29 pm" src="https://cloud.githubusercontent.com/assets/166301/25309065/758bb904-2777-11e7-8007-78cdfb97ea81.png">

http://www.capitol6000.com/thinprint.html

Maybe we can do some design work on top of something like this:

![screen shot 2017-04-22 at 4 17 41 pm](https://cloud.githubusercontent.com/assets/166301/25309070/852bfc70-2777-11e7-8aca-257a2616153d.png)

http://www.flaticon.com/free-icon/rec_189647#term=record&page=1&position=65

**Comment by bcomnes** [comment]
Also neat:

<img width="907" alt="screen shot 2017-04-22 at 4 22 40 pm" src="https://cloud.githubusercontent.com/assets/166301/25309078/ebe23be6-2777-11e7-8ebe-5d1cae37c852.png">

http://www.dafont.com/monogramos.font

**Comment by bcomnes** [comment]
Some more:

http://www.identifont.com/show?BJD

http://www.michaeldoret.com/alphabetsoup

**Comment by ungoldman** [comment]
More ideas: https://www.google.com/search?q=amp+icon&source=lnms&tbm=isch

**Comment by bcomnes** [comment]
Amps are cool, and its in our name.  We could also rename to Hyperwax.

**Comment by bcomnes** [comment]
Or what if we just steal one of the unused iojs logos for the time being. ;) https://github.com/nodejs/node/issues/37

**Comment by bcomnes** [comment]
Capturing drafts from IRC:

Other simple hex logos:

![](https://github.com/depjs/artwork/raw/master/logo-500x500.png)
![](https://webtorrent.io/img/WebTorrent.png)


![](https://usercontent.irccloud-cdn.com/file/U75cmM0u/hyperamp.png)
![](https://usercontent.irccloud-cdn.com/file/biuV6q8r/Screen%20Shot%202017-09-27%20at%2010.50.19%20PM.png)

![](https://usercontent.irccloud-cdn.com/file/XkZg61zE/Screen%20Shot%202017-09-28%20at%207.48.06%20AM.png)

**Comment by bcomnes** [comment]
Looks like inkscape or some SVG editor could do it.

![](http://hexb.in/hexagons/campjs-vi.png)

https://github.com/campjs/campjs-vi/tree/gh-pages/src/svg

**Comment by ungoldman** [comment]
could do what @bcomnes?

**Comment by bcomnes** [comment]
voxel/isomorphic art.

**Comment by bcomnes** [comment]
Hey Bret,

I used Inkscape and found it to be pretty easy to use.  I had used it for other things before that though.  If I remember correctly I set up some isometric guides which made everything a lot easier.  I've checked a couple of the SVGs now and I was hoping that I had left one with the guides and layers intact but it seems not.

I just did a quick google search and I do recall using this article to help get things going :)

https://design.tutsplus.com/tutorials/playing-with-isometric-projection-in-inkscape-to-make-a-minecraft-scene--vector-21757

Hope that helps get you started.

Cheers,
Damon.


On Thu, Oct 12, 2017 at 5:37 AM, Bret Comnes <bret@netlify.com> wrote:
Hi Damon,

I really love the voxel/isomorphic art you did on the camp JS sticker.  

What did you use to make the svgs? 

https://github.com/campjs/campjs-vi/tree/gh-pages/src/svg


Do you have any suggestions on resources that describe techniques or strategies to draw in this style?

Thanks 


Bret Comnes
